app:
  name: BankingApp
  version: 1.0.0
server:
  port: 8080
  host: 127.0.0.1
  apikey: imacantik
database:
  user: root
  password: haha
  host: localhost
  port: 3306
  name: bank
  driver: mysql
